# Exercise 4.9 Part 1 Steps 6-9/

### Step 6 - Combine Customer Data with prepared InstaCart data
### Step 7 - Ensure notebook contains titles, headings, and comments
### Step 8 - Export dataframe as pickle file
### Step 9 - Save Notebook

In [1]:
# Import Libraries

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
# Set Path

path = r'C:\Users\Josh Wattay\anaconda3\Instacart Basket Analysis'

In [3]:
# Import Data

cust_checked = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'cust_checked.pkl'))

In [4]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_4.8.pkl'))

In [5]:
# Drop indicator column from ords_prods_merge

ords_prods_merge.drop(columns = ['_merge'])

,order_id,user_id,order_number,orders_day_of_week,orders_time_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_purchase_cost,spending_flag,median_days_btwn_orders,order_frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,9.000000,Mid-range product,Regularly busy,Average Orders,10,New customer,6.367535,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.000000,Mid-range product,Slowest days,Average Orders,10,New customer,6.367535,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.000000,Mid-range product,Slowest days,Most Orders,10,New customer,6.367535,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.000000,Mid-range product,Slowest days,Average Orders,10,New customer,6.367535,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.000000,Mid-range product,Slowest days,Most Orders,10,New customer,6.367535,Low spender,20.5,Non-frequent customer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,1320836,202557,17,2,15,1.0,43553,2,1,Orange Energy Shots,...,3.699219,Low-range product,Regularly busy,Most Orders,31,Regular customer,6.905718,Low spender,8.0,Frequent customer
32404855,31526,202557,18,5,11,3.0,43553,2,1,Orange Energy Shots,...,3.699219,Low-range product,Regularly busy,Most Orders,31,Regular customer,6.905718,Low spender,8.0,Frequent customer
32404856,758936,203436,1,2,7,NaN,42338,4,0,"Zucchini Chips, Pesto",...,6.898438,Mid-range product,Regularly busy,Average Orders,3,New customer,7.631527,Low spender,15.0,Regular customer
32404857,2745165,203436,2,3,5,15.0,42338,16,1,"Zucchini Chips, Pesto",...,6.898438,Mid-range product,Slowest days,Fewest Orders,3,New customer,7.631527,Low spender,15.0,Regular customer
32404858,3093936,205420,1,4,14,NaN,28818,8,0,Hot Oatmeal Multigrain Raisin,...,10.296875,Mid-range product,Slowest days,Most Orders,16,Regular customer,7.684844,Low spender,13.0,Regular customer

In [13]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_4.9.pkl'))

In [11]:
cust_checked[['Age', 'n_dependants']] = cust_checked[['Age', 'n_dependants']].astype('int8')

### Step 6 - Combine Customer Data with Prepared InstaCart Data

In [ ]:
# Join Data Sets on the user_id column

insta_merge = ords_prods_merge.merge(cust_checked, on = 'user_id', indicator = 'merge_ind')